initial commit
```
$ ./build.sh
++ pwd
++ pwd
+ export OCAMLPATH=/Users/tim.jaeger/saq/ocamlpath-demo/_install/lib:/Users/tim.jaeger/saq/ocamlpath-demo/_install
+ OCAMLPATH=/Users/tim.jaeger/saq/ocamlpath-demo/_install/lib:/Users/tim.jaeger/saq/ocamlpath-demo/_install
+ pushd pkg1
~/saq/ocamlpath-demo/pkg1 ~/saq/ocamlpath-demo
+ dune build --release --build-dir=_build @install
++ pwd
+ dune install --release --build-dir=_build --prefix=/Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/META
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/dune-package
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/foo.ml
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.a
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.cma
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.cmi
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.cmt
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.cmx
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.cmxa
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.ml
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1__Foo.cmi
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1__Foo.cmt
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1__Foo.cmx
Installing /Users/tim.jaeger/saq/ocamlpath-demo/pkg1/../_install/lib/pkg1/pkg1.cmxs
+ popd
~/saq/ocamlpath-demo
+ pushd pkg2
~/saq/ocamlpath-demo/pkg2 ~/saq/ocamlpath-demo
+ dune build --release --build-dir=_build @install
File "lib/dune", line 4, characters 12-16:
4 |  (libraries pkg1))
                ^^^^
Error: Library "pkg1" not found.
-> required by library "pkg2" in _build/default/lib
-> required by _build/default/META.pkg2
-> required by _build/install/default/lib/pkg2/META
-> required by _build/default/pkg2.install
-> required by alias install
(cd _build/default && /Users/tim.jaeger/.opam/default/bin/ocamldep.opt -modules -impl lib/bar.ml) > _build/default/lib/.pkg2.objs/bar.ml.d
File "lib/bar.ml", line 3, characters 19-20:
3 | let url : Sometype = "https://github.com"
                       ^
Error: Syntax error
```